name: cargo_management_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0 # For making HTTP requests
  shared_preferences: ^2.2.2 # For saving the JWT token locally
  provider: ^6.0.5 # For state management
  mongo_dart: ^0.9.3 # For MongoDB database integration
  intl: ^0.18.1 # For internationalization and formatting
  logger: ^2.5.0
  uuid: ^3.0.0
  bson: ^4.0.0
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true